"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
  let g:vundles=['general', 'git'] " programming has an annoying latex module
  let g:neocomplcache_enable_at_startup = 1
  let g:dotvim_colorscheme='molokai'
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  Bundle 'ekalinin/Dockerfile.vim'
  Bundle 'fatih/vim-go'
  Bundle 'tomasr/molokai'
endif

" Customize to your needs...
command! -nargs=* Wrap set wrap linebreak nolist
set wrap linebreak nolist
