# Load Antigen
source $HOME/.dotfiles/zsh/antigen.zsh

# Load Antigen configurations
antigen init $HOME/.dotfiles/zsh/antigenrc

# Theme configuration
source $HOME/.dotfiles/zsh/agkozakrc

# Load docker-based applications/runtimes, like Skype or pdflatex
source $HOME/.dotfiles/zsh/docker-functions

#############################
## Aliases
#############################
alias killx="pkill -15 Xorg"
alias hib="sudo systemctl hibernate"
alias hyb="sudo systemctl suspend-hybrid"
alias gs="git status"
alias resetorigin="git fetch origin && git reset --hard origin/master && git clean -f -d"
alias resetupstream="git fetch upstream && git reset --hard upstream/master && git clean -f -d"
alias ctar="tar -cvzf"
alias utar="tar -xvzf"
if [[ "$OSTYPE" == "darwin"* ]]; then
  wmstop(){
    brew services stop koekeishiya/formulae/yabai
    brew services stop skhd
    brew services stop spacebar
  }
  wmstart(){
    brew services start koekeishiya/formulae/yabai
    brew services start skhd
    brew services start spacebar
  }
  wmrestart(){
    wmstop
    wmstart
  }
  wmreload(){
    wmstop
    wmstart
  }
fi
#############################

pdf(){
  okular ${1:-*.pdf} &
}
wifi(){
  if [ -z $1 ]
  then
    iwconfig wlp3s0
  elif [ $1 = "on" ]
  then
    sudo ifconfig wlp3s0 up
  elif [ $1 = "off" ]
  then
    sudo ifconfig wlp3s0 down
  elif [ $1 = "scan" ]
  then
    echo "TODO: Try scan and scan_results"
    sudo wpa_cli
  else
    echo "only on, off, and scan are supported"
  fi

  # TODO: map to F8
}
help(){
  echo "Useful tidbits:"
  echo "     greenshot -> spectacle/gnome-screenshot"
  echo "         excel -> gnumeric"
  echo "     notepad++ -> atom"
  echo "     foxit pdf -> okular"
  echo " screen layout -> arandr"
  echo "  "
}

# Map caps to escape (tried in xinitrc and it didn't work)
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  setxkbmap -option # unset
  setxkbmap -option caps:escape
fi

# Conscript (APT/Brew for Scala
export PATH=$HOME/.conscript/bin:$PATH
# Giter8 (download git templates)
export PATH=$HOME/.conscript/foundweekends/giter8:$PATH

# Android
export ANDROID_HOME=~/Android/Sdk
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH

if [ -n "$DESKTOP_SESSION" ];then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

export PATH=$HOME/.google-cloud-sdk/bin:$PATH
# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME/.google-cloud-sdk/path.zsh.inc ]; then . $HOME/.google-cloud-sdk/path.zsh.inc; fi
# The next line enables shell command completion for gcloud.
if [ -f $HOME/.google-cloud-sdk/completion.zsh.inc ]; then . $HOME/.google-cloud-sdk/completion.zsh.inc; fi

export N_PREFIX="$HOME/.n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# Vi mode
bindkey -v
# Reduce mode switching time
export KEYTIMEOUT=1

# Better searching in command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M viins '^R' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward
bindkey -M viins '^F' history-incremental-search-forward

# Beginning search with arrow keys (arrows are a bad habit)
#bindkey "^[OA" up-line-or-beginning-search
#bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

export PATH=$HOME/.doom-emacs/bin:$PATH

[ -h '/usr/local/bin/vim' ] && alias vim='/usr/local/bin/vim'
